### ISSUE TITLE
getWireTimeoutFlag Issue

### ISSUE THREAD

**Issue by iGarkov** [pololu/a-star#13]
getWireTimeoutFlag is not working. It returns 0 even if there are no connected devices to the i2c pins. No matter if you use TWI1 or TWI0. I am using pololu a-star with version 5.1

**Comment by DavidEGrayson** [comment]
You might be using `getWireTimeoutFlag` incorrectly.  I suggest posting your entire code along with a description of how you compiled it and tested it, and what results you got.
