### ISSUE TITLE
Virtual Serial port not working after Restarting the Arduino Micor Board

### ISSUE THREAD

**Issue by BeminGhobreal** [pololu/a-star#4]
SO I have an Issue , or at least  I THINK IT IS AN ISSUE WITH THE ARDUINO , correct me if I am mistaken
and please ask question before you decide to close the thread.

After restarting the arduino board using the restart button. the CDC virtual com port breaks and it comes back but it doesn't come back working fully, because I can write to the arduino EEPROM and I see the RX LED is flashing and Also the memory  gets updated, using Serial.read() I read what is in the serial buffer.
When I request data from the ARDUINO using Serial.write()/ print/println Doesn't send data and the TX doesn't flash at all , that is why i know it is an arduino problem not an application or PC issue .
It seems like it doesn't write anything to the Serial Buffer

**Comment by kevin-pololu** [comment]
Which board are you using? What operating system are you running on your computer, and what program are you using to communicate with your board?
