### ISSUE TITLE
Where are the FUSES etc documented?

### ISSUE THREAD

**Issue by Anobium** [pololu/a-star#8]
What were the FUSES documented  ?  What is the setting for WDT etc?

I cannot read these settings from my board.

**Comment by DavidEGrayson** [comment]
The fuse settings depend on which specific A-Star board you have, and you can find the values we use for them by searching for the word "fuses" in [boards.txt](https://github.com/pololu/a-star/blob/master/boards.txt).  To find out what those values mean, you can refer to the appropriate AVR datasheet.
